### ISSUE TITLE
Icon not displayed when deploying a library via Nuget

### ISSUE THREAD

**Issue by georgtauber-durst** [Zeugwerk/Twinpack#143]
In combination with a NuGet-Server the Icon is not displayed.

The icon is integrated according to the official Nuget reference (https://learn.microsoft.com/en-us/nuget/reference/nuspec#icon)

e.g.

```
<package>
  <metadata>
    ...
    <icon>images\icon.png</icon>
    ...
  </metadata>
  <files>
    ...
    <file src="..\icon.png" target="images\" />
    ...
  </files>
</package>
```

**Comment by seehma** [comment]
Currently Twinpack only supports <iconUrl>. We have registered your request for the <icon> tag (as described in the nuspec documentation) as feature request and will reach out back to this issue when its implemented.

**Comment by iadonkey** [comment]
Good news, starting with the next major release of Twinpack (version 1.2.x) the icon tag will be supported as it is documented in the official NuGet "nuspec reference"

![Screenshot_20241207_202106](https://github.com/user-attachments/assets/bfe0fbd8-cec5-4bd3-890c-0b4893aed83a)

Since this is not critical issue, the feature is not backported into Twinpack 1.0.x and we hope to do the release of Twinpack 1.2 in January 2025. Stay tuned and thank you for the feature request
