### ISSUE TITLE
 my library is not published...

### ISSUE THREAD

**Issue by runtimevic** [Zeugwerk/Twinpack#87]
Hello @seehma , @iadonkey , @zeugwerker 

My library is not published...
Is there a log site or where I can see why it is not published?

INFO Publishing package
  INFO Updating plcproj, setting Version=1.0.0.9, Company=TcMotion
  INFO Checking all objects of PLC TcMotion_Library
 ERROR TcMotion_Library does not compile!
  INFO Uploading to Twinpack ...
 ERROR Could not find a part of the path 'E:\BECKHOFF\_TcMotion\Component_Motion_OOP_Axis\TC3_Axis\.Zeugwerk\libraries\TC3.1\TcMotion_Library_1.0.0.9.library'.
  INFO Log in to Twinpack Server successful

thank you, Víctor.

**Comment by iadonkey** [comment]
Twinpack is only uploading libraries when check all objects is going through without errors. According to the log this is not the case here. 
In the output window of your Visual Studio / TcXaeShell there should be some indications why check all object fails. In order to upload the library you have to fix these errors.

However, it is actually a bug that there is no message box popping up to indicate that check all objects failed, we will fix this in the next patch.

**Comment by runtimevic** [comment]
- I had to create this route by hand:
'E:\BECKHOFF_TcMotion\Component_Motion_OOP_Axis\TC3_Axis.Zeugwerk\libraries\TC3.1\
- I had to install the library and leave it in the indicated path:
'E:\BECKHOFF_TcMotion\Component_Motion_OOP_Axis\TC3_Axis.Zeugwerk\libraries\TC3.1\TcMotion_Library_1.0.0.9.library'.

Is this normal? Should these 2 steps be performed?

**Comment by iadonkey** [comment]
No, and this is actually only possible due to the bug I mentioned.
The log message indicates that check all object for your PLC failed and that's why Twinpack wasn't creating the folder and saving to library to this location. The normal process requires that check all objects get through without any errors

**Comment by runtimevic** [comment]
Hi, @iadonkey ,
Yes, this is the problem:

Message:		Compile complete -- 135 errors, 101 warnings

Thanks you, Víctor

**Comment by iadonkey** [comment]
Do you want me to delete the package you uploaded from the Twinpack Server for now? In any case, if the errors are fixed you can simply upload a new version (i.e.1.0.0.10)

**Comment by iadonkey** [comment]
Sure, but I hope you understand that we will prevent the workaround for future releases 😉
